apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: imago-edu
  namespace: "1002890573313"
spec:
  template:
    spec:
      containers:
      - image: us-central1-docker.pkg.dev/imago-edu/containers/imago-edu
        env:
        - name: DB_PASSWORD
          value: "NUEVO_DB_PASSWORD"
        - name: DEBUG
          value: "True"
        - name: GS_BUCKET_NAME
          value: "imago-media"
        - name: SECRET_KEY
          value: "@9=nd*wju3bflkc(=18@fa*zn5=a_*=*fv-i39w4^m4rn@"
        - name: ALLOWED_HOSTS
          value: "imago-edu-1002890573313.us-central1.run.app,.run.app"
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi
      serviceAccountName: 1002890573313-compute@developer.gserviceaccount.com
  traffic:
  - percent: 100
    latestRevision: true
